[package]
name = "astralix"
version = "0.1.0"
authors = ["Johan Eriksson <jae91m@gmail.com>"]
edition = "2021"

[dependencies]
specs = "0.17"
specs-derive = "0.4.1"
rand = "0.8.4"

[dependencies.sdl2]
version = "0.34.5"
default-features = false
features = ["image"]
