[package]
name = "astralix"
version = "0.1.0"
authors = ["Johan Eriksson <jae91m@gmail.com>"]
edition = "2021"

[dependencies]
# bevy = { git = "https://github.com/bevyengine/bevy", rev = "615d43b9989c45cdd310d4bea1aaa3fc285b2782" }
# bevy = { git = "https://github.com/bevyengine/bevy" }

bevy = { version = "0.5.0", features = ["dynamic"] }
# bevy = "0.5"
# 615d43b9989c45cdd310d4bea1aaa3fc285b2782
